/**
 * This class is a non-oop lottery simulation program,first the program will generate 6 non-repeat regular number and a 1 encore number,
 * then user will be asked to enter 6 regular number from 1-30 and
 * a encore number from 1-7,if user enters a repeating regular number,the program will ask the user to enter a non repeat number,
 * after user enters all regular and encore number the program will give a winning result also with a jack pot number.
 * @author Mutian Hou
 * @version 1.0
 * @since 11.0.17
 * @see java.util.Random
 * @see java.util.Scanner
*/
import java.util.Random;
import java.util.Scanner;

public class LuckyLottery {
//create a non changeable container to save 7 Integer values
public final static int[] LUCKY_NUMBER = new int[7];
//regular number range
public final static int REG_NUMBER = 30;
//encore number range
public final static int ENCORE_NUMBER = 7;
static{
	Random rc = new Random();
	for(int i = 0;i< LUCKY_NUMBER.length -1; i++){
		while(true){
	//generate random number from 1-REG_NUMBER length
			int number = rc.nextInt(REG_NUMBER )+1;
			
			boolean flag = true;
		//loop again if the program generate a same regular number
		for(int j = 0;j < i;j++) {
			if(LUCKY_NUMBER[j] == number) {
				flag = false;
				break;
			  }
			}
		if(flag) {
			LUCKY_NUMBER[i] = number;
			break;
		}
	   }
	}
	//save the random encore number to the last of array LUCKY_NUMBER
	int encore = rc.nextInt(ENCORE_NUMBER)+1;
	LUCKY_NUMBER[6] = encore;
	}

/**
 * This is the entry point for the application,it gives the number you entered and 
 * a winning number generated by the program,then the program gives user message whether user win a prize 
 * @param args Command line arguments are not used by this program.
 */
public static void main(String[] args) {
    	int [] yourNumber = enterYourNumber();
    	System.out.println("your number is");
    	showNumber(yourNumber);
    	System.out.println("Jackpot number is");
    	showNumber(LUCKY_NUMBER);
    	winAPrize(yourNumber,LUCKY_NUMBER);
   }


/**
 *this method compare user input numbers and winning numbers and then give a winning result.
 *@param yourNumber the array of user input
 *@param LUCKY_NUMBER the array of Integers that generated by program
*/
public static void winAPrize(int[] yourNumber , int[] LUCKY_NUMBER) {
	int number = 0;
	int encore = 0;
	for(int i = 0;i < yourNumber.length -1;i++) {
		for(int j = 0; j < LUCKY_NUMBER.length -1; j++) {
			if(yourNumber[i] == LUCKY_NUMBER[j]) {
				number++;
				break;
			}
		}
	}
	encore = yourNumber[6]==LUCKY_NUMBER[6]? 1:0;
	
	if(encore==1 && number==1) {
		System.out.println("free play");
	}else if(encore==1 && number ==2) {
		System.out.println("10 dollars !");
	}else if(encore==1 && number==3) {
		System.out.println("100 dollars!");
	}else if(encore==1 && number==4 || encore==0 && number ==5) {
		System.out.println("1000 dollars !");
	}else if(encore==1 && number==5 || encore==0 && number==6) {
		System.out.println("10,000 dollars!");
	}else if(encore==1 && number==6 || encore==0 && number==7) {
		System.out.println("100,000 dollars!");
	}else if(encore==1 && number==7) {
		System.out.println("congrats!set for life!");
	}else {
		System.out.println("not a winner");
	}
}
//print each element of an array
public static void showNumber(int[]arr) {
	
	for(int i =0;i <arr.length;i++) {
    	   System.out.print(arr[i]+"\t");
  
	}         
	System.out.println();
}
/**
This portion of your code prompt user to enter numbers and return an array that saves the numbers.
@return an array that saves user input numbers
*/
public static int[] enterYourNumber() {
    	 Scanner sc = new Scanner(System.in);
       	int [] yourNumber = new int[7];
       	for(int i = 0;i <yourNumber.length-1;i++ )
       	while(true) {
       		System.out.println("please enter your \t" + (1+i) +"\t number from 1-30(no repeating)");
       		
        int number = sc.nextInt();
        
       	boolean bl =checkRepeatingNumber(yourNumber,number);
       	if(bl == true){
       		if(number > 0 && number < 31) {
       		yourNumber[i] = number;
       		break;
       		}else {
       			System.out.println("please enter a number from 1-30");
       		}	
       	
       	}else {
       		System.out.println("please enter a no repeating number");
       	}
      }
        System.out.println("please enter your encore number(1-7)");
           while(true){
       	 int encore = sc.nextInt();
           if(encore >= 1 && encore <=16) {
                  yourNumber[6] = encore;
                  break;
          }else {
        	  System.out.println(" please enter encore number in(1-7)");
          }
       	}   
           return yourNumber;
   }

/**
 This portion of your code checks the repeat numbers and gives a boolean result.
 @param arr Integer array
 @param n an Integer  
 @return an boolean result.
*/
public static boolean checkRepeatingNumber(int[]arr,int n) {
	for(int i =0;i< arr.length-1;i++) {
		if(arr[i] == n) {
			return false;
		}
	}
           return true;
}

}
